name: Continuous Integration

on:
  pull_request:
    branches:
      - main
    paths:
      - infra/**
      - src/**
      - tests/**
  workflow_dispatch:

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  lint-and-publish-bicep:
    name: Lint and Publish Bicep
    uses: ./.github/workflows/lint-and-publish-bicep.yml
