name: End-to-End Test

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: "The environment to use for E2E testing"
        required: true
        type: string
      BUILD_VERSION:
        description: "The version of the build to deploy to the application resources"
        required: true
        type: string
      AZURE_LOCATION:
        description: "The Azure region to deploy the application resources to"
        required: true
        type: string
      AZURE_ENV_NAME:
        description: "The name of the Azure environment"
        required: true
        type: string

    outputs:
      WEBAPP_DEFAULT_HOST_NAME:
        description: "Default hostname of the deployed Web App"
        value: ${{ jobs.provision-infrastructure.outputs.WEBAPP_DEFAULT_HOST_NAME }}
      APPLICATION_GATEWAY_PUBLIC_IP_ADDRESS:
        description: "Public IP Address of the Application Gateway"
        value: ${{ jobs.provision-infrastructure.outputs.APPLICATION_GATEWAY_PUBLIC_IP_ADDRESS }}
      LOG_ANALYTICS_WORKSPACE_ID:
        description: "Resource ID of the Log Analytics Workspace"
        value: ${{ jobs.provision-infrastructure.outputs.LOG_ANALYTICS_WORKSPACE_ID }}
      APPLICATION_INSIGHTS_CONNECTION_STRING:
        description: "Connection string for Application Insights"
        value: ${{ jobs.provision-infrastructure.outputs.APPLICATION_INSIGHTS_CONNECTION_STRING }}
      VM_NAME_OUTPUT:
        description: "Name of the deployed Virtual Machine"
        value: ${{ jobs.provision-infrastructure.outputs.VM_NAME_OUTPUT }}
      POSTGRES_SERVER_FQDN:
        description: "Fully Qualified Domain Name (FQDN) of the PostgreSQL server"
        value: ${{ jobs.provision-infrastructure.outputs.POSTGRES_SERVER_FQDN }}

    secrets:
      AZURE_TENANT_ID:
        description: "The Azure tenant ID to use for authentication to Azure for deployment"
        required: true
      AZURE_SUBSCRIPTION_ID:
        description: "The Azure subscription ID to use for authentication to Azure for deployment"
        required: true
      AZURE_CLIENT_ID:
        description: "The Azure client ID to use for authentication to Azure for deployment"
        required: true

jobs:
  validate-infrastructure:
    name: Validate Infrastructure
    uses: ./.github/workflows/validate-infrastructure.yml
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      BUILD_VERSION: ${{ inputs.BUILD_VERSION }}
      AZURE_LOCATION: ${{ inputs.AZURE_LOCATION }}
      AZURE_ENV_NAME: ${{ inputs.AZURE_ENV_NAME }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}

  provision-infrastructure:
    needs: validate-infrastructure
    uses: ./.github/workflows/provision-infrastructure.yml
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      BUILD_VERSION: ${{ inputs.BUILD_VERSION }}
      AZURE_LOCATION: ${{ inputs.AZURE_LOCATION }}
      AZURE_ENV_NAME: ${{ inputs.AZURE_ENV_NAME }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}

  # Placeholder for E2E test job(s)
  e2e-tests:
    needs: provision-infrastructure
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Echo deployed resources
        run: |
          echo "Web App Host: ${{ needs.provision-infrastructure.outputs.WEBAPP_DEFAULT_HOST_NAME }}"
          echo "Application Gateway IP: ${{ needs.provision-infrastructure.outputs.APPLICATION_GATEWAY_PUBLIC_IP_ADDRESS }}"
          echo "Log Analytics Workspace: ${{ needs.provision-infrastructure.outputs.LOG_ANALYTICS_WORKSPACE_ID }}"
          echo "Application Insights: ${{ needs.provision-infrastructure.outputs.APPLICATION_INSIGHTS_CONNECTION_STRING }}"
          echo "VM Name: ${{ needs.provision-infrastructure.outputs.VM_NAME_OUTPUT }}"
          echo "PostgreSQL FQDN: ${{ needs.provision-infrastructure.outputs.POSTGRES_SERVER_FQDN }}"

  delete-infrastructure:
    needs: [provision-infrastructure, e2e-tests]
    if: always()
    uses: ./.github/workflows/delete-infrastructure.yml
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      AZURE_LOCATION: ${{ inputs.AZURE_LOCATION }}
      AZURE_ENV_NAME: ${{ inputs.AZURE_ENV_NAME }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
